/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:4b410fe8-90ae-4465-b4a2-3bc7391ed87e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_rvl37NfFX",
    "aws_user_pools_web_client_id": "1qqscurj7u9dbak5hahapcuu2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://d4bfwm43gzcb5fne2cremknsha.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gsz3jb52obfq3lt264u4qmbusy",
    "aws_user_files_s3_bucket": "amplifyapp5cdcb4556e5244528410b78875370b6432032-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
